### ISSUE TITLE
Failed to open JTAG Cable for CTP6

### ISSUE THREAD

**Issue by pklabbers** [uwcms/cms-calo-layer1#44] opened 2013-11-06 09:27 UTC
I am trying to replicate what Maria did before Evan left.  It is described here  https://github.com/uwcms/cms-calo-layer1/wiki/The-CTP6#loading-the-front-end-payload-with-xmd 

I cannot get the make payload to work, I get:

XMD% ERROR: Failed to Open JTAG Cable
    Cable target is not connected to the host

The driver is fine, the green light is on on the USB-JTAG box.  Everything looks plugged in.  The switch is down (I tried both positions) on the JTAG input.  I traced 
the USB cable back to l1ts-rct-01, that seems fine, all the flying leads seem to be plugged in to the ribbon cable.  Any suggestions?  

Am I missing some critical step?

Thanks,
Pam

**Comment by mcepeda** [comment] 2013-11-06 13:20
Hi Pam,

I have been going through the wiki and I think everything I did is contained there. I can also see the USB from l1ts-rct-02, so it is somehow connected.

Can it be a code issue? Have you updated to the latest code in the repository? I will be there tomorrow morning, since I still have the version of the code that we used before Evan left untouched in my setup we can test it to see if this was caused by a change.

(Just to know, after what command does it stop?)

Maria

**Comment by pklabbers** [comment] 2013-11-06 13:29
The XMD command run on l1ts-rct-01 (the JTAG controller going to the CTP6 is connected to that PC), do I instead need to use the USB (from the hub) on l1ts-rct-02?  Anyhow, here is the full text:

make upload
echo "connect mb mdm -debugdevice deviceNr 2; rst; connect mb mdm -debugdevice deviceNr 2; dow payload.elf; run" | xmd
Xilinx Microprocessor Debugger (XMD) Engine
Xilinx EDK 14.4 Build EDK_P.49d
Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

XMD% 
XMD% ERROR: Failed to Open JTAG Cable
    Cable target is not connected to the host

**Comment by mcepeda** [comment] 2013-11-06 13:43
You're right, this should be done from l1ts-rct-01 - sorry.

I do get the same exact error with my installation, so it is not a change in code. 

Was any cable moved last week in the operations?

**Comment by pklabbers** [comment] 2013-11-06 13:50
I put the front panel on, but then took it off again yesterday thinking that it was still interfering.  So there were a couple of power cycles.

**Comment by pklabbers** [comment] 2013-11-06 13:51
I did make sure there were clocks coming from the AMC13 again, following instructions that I had been e-mailed, now they are copied to the CTP6 page.

**Comment by tsarangi** [comment] 2013-11-06 22:52
So, did you guys figure this one out ? It might be that the drivers on the pc are corrupted, so you might have to install them again. I had this problem here in Chmbrln with the pc connected to CTP6. The driver install script is in here,
/PATH/TO//Xilinx/14.4/ISE_DS/common/bin/lin64/install_script/install_drivers/install_drivers

**Comment by mcepeda** [comment] 2013-11-07 09:25
Hi Tapas,

Thanks!
That fixed it.

In the README of the directory you sent (/opt/Xilinx/14.4/ISE_DS/common/bin/lin/install_script/install_drivers/readme.txt) it explains that:

NOTE: By default, access to windrvr6 is restricted to root only. This step grants group and user access to the driver. However, if you reboot your system, access to the driver will revert back to root-only and you will have to repeat step #7 (you do not have to rerun the installation script). 

(7. Change permissions on the USB / PC4 driver by typing: chmod 666 /dev/windrvr6.)

I changed the permissions of that file and now I can "make upload".

Maria

**Comment by mcepeda** [comment] 2013-11-07 16:32
I tested the full set of instructions and it worked on my side.

I included the problem (&solution) in the CTP6 wiki for instructions (https://github.com/uwcms/cms-calo-layer1/wiki/The-CTP6#known-problems--solutions)

@pklabbers , did you try? Can I close the issue?

Maria

**Comment by pklabbers** [comment] 2013-11-07 16:39
Hi Maria,
I'll give it a shot again tomorrow, and then close this if it works. 
Thanks for all the help,
Pam

**Closed as completed** 2013-11-08 12:20 UTC
Labels: question
