### ISSUE TITLE
oRSC Locks up VME

### ISSUE THREAD

**Issue by ekfriis** [uwcms/cms-calo-layer1#24] opened 2013-10-16 15:29 UTC
We (@dabelknap and @pklabbers and @mcepeda) are trying to write to a single address from the VME PC and read it out of the oRSC backend via XMD.

We use a very old tool called `vmedia` which gives you a console which lets you peek/poke into vmedia.   Steps to do this, following [1]:
1. connect to ayinger (this has the VME PC)
2. get the latest cms-calo-layer1 (maybe create a fresh area)
3. "make orscbebits" - uploads the latest bitfile in cms-calo-layer1/bitfiles to the ORSC backend (double check this is the correct one)
4. the lights are no longer blinky on the front
5. export CAEN_LINK=1 to use lower crate (double check this is what you want)
6. source /cms/cmslab/trigger_upgrade/cactusprojects/rct/environment.sh to get vmedia binary in PATH
7. run vmedia, then "A32" (32-bit addressing) then "lpoke 1 0000 DEADBEEF" (poke 1 long word [32-bits] into address 0000 with value DEADBEEF)
8. **vmedia returns an error - expected behavior: it should not**
9. Make sure the XMD debugger is hooked up between ayinger and the oRSC.  Then connect via XMD to the ORSC backend `connect mb mdm -debugDevice deviceNr 1;` 
10. **expected behavior: see DEADBEEF when you `mrd 0x00000000`**

NB that after flashing the bitfile with XMD, the CAEN controller DTK (data transfer ack) LED is lit, when it shouldn't be according to our thinking.  Perhaps this is a clue.

cc @mathiasblake @nwoods @tsarangi 

[1] https://twiki.cern.ch/twiki/bin/view/CMS/RCTAtChamberlin

**Comment by nwoods** [comment] 2013-10-22 17:20
ORSC is connected to Spaten, not Ayinger, and its JTAG cable can only reach Spaten, so we'll have to use that. 

Also, ORSC is in the top crate, not the bottom crate. The RCTAtChamberlin twiki agrees that we should use `CAEN_LINK=1`, but when I do that, it just says that VME can't connect. 

With those caveats: using `CAEN_LINK=0`, I reproduce your error:

```
nwoods@spaten /afs/hep.wisc.edu/cms/nwoods/orsc_test/cms-calo-layer1  master$ vmedia
VMEDia>  A32
Booting from CAEN link and board 0 0
VMEDia>  lpoke 1 0000 DEADBEEF
CAEN could not write 0
Failed to write to VME
```

**Comment by ekfriis** [comment] 2013-10-22 17:23
Did you flash the newer bitfile? (fpga -f)?  Are the lights till blinky?

You need to be very sure about what CAEN_LINK you pointing to otherwise you
will waste your time - maybe see if the behavior changes if you unplug the
fiber going into non-oRSC crate.

**Comment by dabelknap** [comment] 2013-10-23 09:41
I tried the following procedure on the oRSC at 904 with the October 22 bitfiles provided by @mathiasblake. (Using commit 8a52788)

``` sh
$ make orscbebits
Programming back end bitfile
    <... XMD printout ...>
Successfully downloaded bit file.
$ export CAEN_LINK=0
$ export VME_CONTROLLER=CAEN
$ vmedia
VMEDia>  A32
Booting from CAEN link and board 0 0
VMEDia>  poke 1 0000 A5A5
CAEN could not write 0
Failed to write to VME
VMEDia>  exit
Bye
```

After running `poke`, the CAEN controller was showing the correct `1010 0101 1010 0101` pattern, and `BERR` was red (see image below).
![img_0165](https://f.cloud.github.com/assets/1830592/1388791/03a5966a-3bc7-11e3-9dd9-9beefa06a548.jpg)

**Comment by ekfriis** [comment] 2013-10-23 09:49
NB the CAEN_LINK environment variable will not necessarily be the same at
Chamberlin!

**Comment by dabelknap** [comment] 2013-10-23 14:16
@mathiasblake With the October 22 bitfiles, `caenRCTBoot` is unable to boot the cards. Booting works with the  default bitfiles (the ones Tom placed on the oRSC).
- w/ Oct 22 bitfiles:

``` sh
$ caenRCTBoot
Booting from CAEN link and board 0 0
INFO - CAEN reset
```
- w/ default bitfiles:

``` sh
$ caenRCTBoot
Booting from CAEN link and board 0 0
INFO - CAEN reset
INFO - Programmed card 10000000
INFO - IRQ checked - mask =
INFO - Programmed card 11000000
INFO - IRQ checked - mask =
INFO - Programmed card 12000000
INFO - IRQ checked - mask =
INFO - Programmed card 13000000
INFO - IRQ checked - mask =
INFO - Programmed card 14000000
INFO - IRQ checked - mask =
INFO - Programmed card 15000000
INFO - IRQ checked - mask =
INFO - Programmed card 16000000
INFO - IRQ checked - mask =
INFO - Programmed card 17000000
INFO - IRQ checked - mask =
INFO - Programmed card 18000000
INFO - IRQ checked - mask =
INFO - Programmed card 19000000
INFO - IRQ checked - mask =
INFO - Programmed card 1a000000
INFO - IRQ checked - mask =
INFO - Programmed card 1b000000
INFO - IRQ checked - mask =
INFO - Programmed card 1c000000
INFO - IRQ checked - mask =
INFO - Programmed card 1d000000
INFO - IRQ checked - mask =
INFO - Programmed card 1e000000
INFO - IRQ checked - mask =
INFO - Programmed card 1f000000
```

**Comment by ekfriis** [comment] 2013-10-23 15:21
cc @mathiasblake @pklabbers

More data points:

If we caenRCTBoot the crate, with Tom's bitfiles, we can write/read from VME addresses on the receiver cards:

```
VMEDia>  poke 1 16000000 AB
VMEDia>  dump 1 16000000 
16000000 -> 02AB
VMEDia>  poke 1 16000000 EF
VMEDia>  dump 1 16000000 
16000000 -> 02EF
```

(this is successfull)

Now if I upload the new oRSC bitfiles (`make orscbitfiles`), I can still poke and dump w/o VME crashing. (note I _cannot_ run caenRCTBoot, it will crash), but get strange behavior:

```
VMEDia>   poke 1 16000000 AB
Booting from CAEN link and board 0 0
VMEDia>  dump 1 16000000 
16000000 -> 02AD
VMEDia>  poke 1 16000000 EF
VMEDia>   dump 1 16000000 
16000000 -> 02AD
VMEDia>   dump 1 16000000 00
16000000 -> 02AD
VMEDia>  poke 1 16000000 00
VMEDia>   dump 1 16000000 
16000000 -> 022D
```

So now it is always stuck at 0xAD/0x2D, no matter what I write.

**Comment by dabelknap** [comment] 2013-10-31 09:39
@ekfriis @mathiasblake
I just tried the Oct 31 BE bit file at 904. The crate is unable to boot:

``` sh
$ caenRCTBoot
Booting from CAEN link and board 0 0
INFO - CAEN reset
ERROR - CAEN failed to issue IACK
```

Poking with vmedia doesn't work either:

``` sh
$ vmedia
VMEDia>  A32
Booting from CAEN link and board 0 0
VMEDia>  poke 1 16000000 AB
CAEN could not write 16000000
Failed to write to VME
VMEDia>
```

The errors only occur if I flash the BE bitfile.

**Comment by ekfriis** [comment] 2013-10-31 09:53
@pklabbers, are you at 904? can you try cycling the crate?  maybe the
caenRCTBoot is messing up the oRSC - Austin, can you try doing the vmedia
check before you run caenRCTBoot?

**Comment by dabelknap** [comment] 2013-10-31 09:54
We are both at 904 now, actually. We did try cycling the crate.

**Comment by ekfriis** [comment] 2013-10-31 09:58
Does the DTK light come on like before?

**Comment by dabelknap** [comment] 2013-10-31 10:03
DTK lights is on for both `caenRCTBoot` and the `vmedia` test.

**Comment by ekfriis** [comment] 2013-10-31 10:10
Any other lights?  Before it was only DTK.

**Comment by dabelknap** [comment] 2013-10-31 10:18
IRQ2 is on also.

**Comment by pklabbers** [comment] 2013-10-31 10:20
IRQ2 is normal after a power cycle or VME Reset.  The cards need to be programmed again.

**Comment by dabelknap** [comment] 2013-11-01 09:17
@mathiasblake 
With the latest BE bitfile (the one posted at Oct 31 14:24), booting the crates seems to work fine:

``` sh
$ caenRCTBoot
Booting from CAEN link and board 0 0
INFO - CAEN reset
INFO - Programmed card 10000000
INFO - IRQ checked - mask =
INFO - Programmed card 11000000
...
```

Writing to VME memory seems to be fine as well, but I get an error when I attempt to read it.

``` sh
$ vmedia
VMEDia>  poke 1 1000 A5A5
Booting from CAEN link and board 0 0
VMEDia>  dump 1 1000 A5A5
CAEN could not read 1000status = ffffffff
Failed to read from VME
00001000 -> FFFF
VMEDia>
```

I just saw Evan's email about this, so I guess he saw the same thing.

**Comment by mathiasblake** [comment] 2013-11-01 15:04
You are not reading from a valid read address.

**Comment by dabelknap** [comment] 2013-11-01 15:16
Ah, okay, thanks. I neglected the base address. Although, I am not sure why the value I am writing is getting truncated.

``` sh
$ vmedia
VMEDia>  A32
Booting from CAEN link and board 0 0
VMEDia>  poke 1 10000000 A5A5
VMEDia>  dump 1 10000000
10000000 -> 00A5
```

**Comment by ekfriis** [comment] 2013-11-01 18:18
ghost evan from beyond the grave says that he thinks you should use lpoke,
ask pam

**Comment by tsarangi** [comment] 2013-11-01 18:24
@ekfriis 
ghost Evan seems not enjoying the after death silence, waiting eagerly for the reincarnation... :)

**Comment by dabelknap** [comment] 2013-11-01 19:14
@ZombieEvan I already tried `lpoke`, but it only put more zeros on the return value.

**Comment by mathiasblake** [comment] 2013-11-01 19:24
Austin,

The addresses from my email need to be shifted left by 1 bit in order to work.  Try doing a peek at addr 0x2000

-Mathias

**Comment by dabelknap** [comment] 2013-11-01 21:56
@mathiasblake Can you give me an example `vmedia` session that I can try to reproduce? It doesn't make sense to me why the addresses should be shifted by 1 bit.

**Comment by dabelknap** [comment] 2013-11-06 13:55
@mathiasblake, I tried shifting the bit, but I am still having problems:

``` sh
$ vmedia
VMEDia>  A32
Booting from CAEN link and board 0 0
VMEDia>  poke 1 2000 A5A5
CAEN could not write 2000
Failed to write to VME
VMEDia>  poke 1 20000000 A5A5
VMEDia>  dump 1 20000000
CAEN could not read 20000000status = ffffffff
Failed to read from VME
20000000 -> FFFF
VMEDia>
```

**Comment by dabelknap** [comment] 2013-11-06 13:56
Also, once this issue gets sorted out, I can start testing the VMEPC/oRSC interface on the hardware.

**Comment by mathiasblake** [comment] 2013-11-06 15:27
Hi Austin,

You are still reading and writing from the wrong addresses:

for VME you can WRITE to the following ranges:
0x0 - 0xffe
0x1000 - 0x1ffe

for VME you can READ from the following ranges:
0x2000 - 0x2ffe
0x3000 - 0x3ffe

example:

vmedia poke 1 0 abcd
xmd mrd 0x10000000  When you do this read you should see 0xabcd

xmd mwr 0x10001000 0x1234
vmedia dump 1 2000  when you do this dump you should see 0x1234

-Mathias

**Comment by dabelknap** [comment] 2013-11-06 15:41
Thanks! This is what I needed. I remember you mentioning something about this at the meeting, but is the bit-shifting of the addresses for `vmedia` only, or do I need to do this in general?

**Comment by mathiasblake** [comment] 2013-11-06 15:53
That I am not sure about.  You’ll have to just give it a try and see.  I suspect you will, but I can’t be certain.

-Mathias

**Comment by dabelknap** [comment] 2013-11-07 10:26
It would appear that the VMEController class I am using requires the bit-shifted addresses. The trouble I am having is that it will only accept `cvD16` (rather than `cvD32`) for the datawidth. So, `poke` works fine, but `lpoke` does not.

``` sh
$ vmedia
VMEDia>  poke 1 0000 CAFE
Booting from CAEN link and board 0 0
VMEDia>  A32
VMEDia>  lpoke 1 0000 CAFEBABE
CAEN could not write 0
Failed to write to VME
```

Were we planning on using 32-bit words, or is this not the case?

**Comment by mathiasblake** [comment] 2013-11-07 16:10
The VME interface in the RCT is 16-bit.

**Comment by dabelknap** [comment] 2013-11-07 16:12
Okay, so I should probably be using `uint16_t` for data buffers?

Originally, I was using `uint32_t` for everything. I'm not sure how difficult it will be to make the conversion.

**Comment by dabelknap** [comment] 2013-11-08 10:48
@mathiasblake 
@pklabbers 
Actually, I think making the switch to 16-bit shouldn't be a problem. At this point I can read/write single words between VME and the oRSC just fine.

I am having some difficultly finding the correct way to transfer a buffer of words across VME. I could try a VME multiwrite and write the words to consecutive addresses. However, I need to know what the step-size of the VME addresses are. It appears to me like 0x0 to 0x1 (in microblaze) is a 4-bit step; is this correct?

Or, do you have an alternative recommendation for how to transfer a buffer of values across VME?

**Comment by dabelknap** [comment] 2013-11-13 12:20
Since VME read/write and block read/write appear to be working, I will close this issue. Thanks!

**Closed as completed by dabelknap** 2013-11-13 12:20 UTC
